package com.example.aiqa.service;

import com.example.aiqa.domain.AutomationTest;
import com.example.aiqa.repository.AutomationTestRepository;
import com.example.aiqa.service.ai.OpencodeAIProviderService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.util.*;

@Service
public class AutomationEngineService {
    
    private static final String SCRIPTS_DIR = "automation-scripts";
    private static final String SCREENSHOTS_DIR = "automation-screenshots";
    
    @Autowired
    private AutomationTestRepository repository;
    
    @Autowired
    private OpencodeAIProviderService aiService;
    
    @Autowired
    private BrowserAutomationService browserService;
    
    public AutomationTest createTest(String name, String url, String instruction) {
        AutomationTest test = new AutomationTest();
        test.setName(name);
        test.setUrl(url);
        test.setInstruction(instruction);
        test.setStatus(AutomationTest.TestStatus.PENDING);
        return repository.save(test);
    }
    
    @Transactional
    public AutomationTest generateScriptOnly(String name, String url, String instruction, String username, String password) {
        AutomationTest test = createTest(name, url, instruction);
        
        try {
            Object analysis = browserService.analyzePage(url);
            
            String script = aiService.generateTestScript(
                null, instruction, url, username, password, null
            );
            
            String safeName = sanitizeFileName(name);
            Path scriptPath = Paths.get(SCRIPTS_DIR, safeName + ".spec.ts");
            Files.createDirectories(scriptPath.getParent());
            Files.writeString(scriptPath, script);
            
            test.setScript(script);
            test.setStatus(AutomationTest.TestStatus.PENDING);
            test.setLogs("Script generated by AI based on page analysis");
            
        } catch (Exception e) {
            test.setStatus(AutomationTest.TestStatus.ERROR);
            test.setLogs("Error: " + e.getMessage());
        }
        
        return repository.save(test);
    }
    
    @Transactional
    public AutomationTest analyzeAndGenerate(String name, String url, String instruction, String username, String password) {
        AutomationTest test = createTest(name, url, instruction);
        
        try {
            Object pageAnalysis = browserService.analyzePage(url);
            
            String script = aiService.generateTestScript(
                null, instruction, url, username, password, null
            );
            
            String safeName = sanitizeFileName(name);
            Path scriptPath = Paths.get(SCRIPTS_DIR, safeName + ".spec.ts");
            Files.createDirectories(scriptPath.getParent());
            Files.writeString(scriptPath, script);
            
            test.setScript(script);
            test.setStatus(AutomationTest.TestStatus.PENDING);
            test.setLogs("AI analyzed page and generated Playwright script dynamically");
            
        } catch (Exception e) {
            test.setStatus(AutomationTest.TestStatus.ERROR);
            test.setLogs("Error: " + e.getMessage());
        }
        
        return repository.save(test);
    }
    
    public List<AutomationTest> getAllTests() {
        return repository.findByOrderByCreatedAtDesc();
    }
    
    public AutomationTest getTest(Long id) {
        return repository.findById(id).orElse(null);
    }
    
    public void deleteTest(Long id) {
        repository.deleteById(id);
    }
    
    public List<AutomationTest> getTestHistory() {
        return repository.findByOrderByCreatedAtDesc();
    }
    
    private String sanitizeFileName(String name) {
        return name.toLowerCase()
            .replaceAll("[^a-z0-9]+", "-")
            .replaceAll("^-|-$", "")
            .substring(0, Math.min(50, name.length()));
    }
    
    public String getScreenshotPath() {
        return SCREENSHOTS_DIR;
    }
}